version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"

    command: >
      sh -c "python manage.py migrate &&
        gunicorn --bind 0:8000 --workers 5 --log-level debug proj.wsgi"

    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: .

    command: celery -A proj worker -l info

    depends_on:
      - app

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/app.conf:/etc/nginx/conf.d/app.conf
      - ./src/static/:/static
    ports:
      - "80:80"
    depends_on:
      - app